<div>
    @livewire('user-interface.slider')
    @livewire('user-interface.happy-client')
    @include('livewire.user-interface.whatWeDo.what-we-do')
    @livewire('user-interface.projects.project-detail')
    @livewire('user-interface.services.service')
    @livewire('user-interface.testimonial')
    @livewire('user-interface.contact-us.contact-us')
    @livewire('user-interface.newsletters')
</div>
